=begin
#EVE Stable Infrastructure (ESI) - tranquility

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2020-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'date'
require 'time'

module ESI
  class AlliancesAllianceIdGet < ApiModelBase
    # ID of the corporation that created the alliance
    attr_accessor :creator_corporation_id

    # ID of the character that created the alliance
    attr_accessor :creator_id

    attr_accessor :date_founded

    # the executor corporation ID, if this alliance is not closed
    attr_accessor :executor_corporation_id

    # Faction ID this alliance is fighting for, if this alliance is enlisted in factional warfare
    attr_accessor :faction_id

    # the full name of the alliance
    attr_accessor :name

    # the short name of the alliance
    attr_accessor :ticker

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'creator_corporation_id' => :'creator_corporation_id',
        :'creator_id' => :'creator_id',
        :'date_founded' => :'date_founded',
        :'executor_corporation_id' => :'executor_corporation_id',
        :'faction_id' => :'faction_id',
        :'name' => :'name',
        :'ticker' => :'ticker'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'creator_corporation_id' => :'Integer',
        :'creator_id' => :'Integer',
        :'date_founded' => :'Time',
        :'executor_corporation_id' => :'Integer',
        :'faction_id' => :'Integer',
        :'name' => :'String',
        :'ticker' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ESI::AlliancesAllianceIdGet` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ESI::AlliancesAllianceIdGet`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'creator_corporation_id')
        self.creator_corporation_id = attributes[:'creator_corporation_id']
      else
        self.creator_corporation_id = nil
      end

      if attributes.key?(:'creator_id')
        self.creator_id = attributes[:'creator_id']
      else
        self.creator_id = nil
      end

      if attributes.key?(:'date_founded')
        self.date_founded = attributes[:'date_founded']
      else
        self.date_founded = nil
      end

      if attributes.key?(:'executor_corporation_id')
        self.executor_corporation_id = attributes[:'executor_corporation_id']
      end

      if attributes.key?(:'faction_id')
        self.faction_id = attributes[:'faction_id']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'ticker')
        self.ticker = attributes[:'ticker']
      else
        self.ticker = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @creator_corporation_id.nil?
        invalid_properties.push('invalid value for "creator_corporation_id", creator_corporation_id cannot be nil.')
      end

      if @creator_id.nil?
        invalid_properties.push('invalid value for "creator_id", creator_id cannot be nil.')
      end

      if @date_founded.nil?
        invalid_properties.push('invalid value for "date_founded", date_founded cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @ticker.nil?
        invalid_properties.push('invalid value for "ticker", ticker cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @creator_corporation_id.nil?
      return false if @creator_id.nil?
      return false if @date_founded.nil?
      return false if @name.nil?
      return false if @ticker.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] creator_corporation_id Value to be assigned
    def creator_corporation_id=(creator_corporation_id)
      if creator_corporation_id.nil?
        fail ArgumentError, 'creator_corporation_id cannot be nil'
      end

      @creator_corporation_id = creator_corporation_id
    end

    # Custom attribute writer method with validation
    # @param [Object] creator_id Value to be assigned
    def creator_id=(creator_id)
      if creator_id.nil?
        fail ArgumentError, 'creator_id cannot be nil'
      end

      @creator_id = creator_id
    end

    # Custom attribute writer method with validation
    # @param [Object] date_founded Value to be assigned
    def date_founded=(date_founded)
      if date_founded.nil?
        fail ArgumentError, 'date_founded cannot be nil'
      end

      @date_founded = date_founded
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] ticker Value to be assigned
    def ticker=(ticker)
      if ticker.nil?
        fail ArgumentError, 'ticker cannot be nil'
      end

      @ticker = ticker
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          creator_corporation_id == o.creator_corporation_id &&
          creator_id == o.creator_id &&
          date_founded == o.date_founded &&
          executor_corporation_id == o.executor_corporation_id &&
          faction_id == o.faction_id &&
          name == o.name &&
          ticker == o.ticker
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [creator_corporation_id, creator_id, date_founded, executor_corporation_id, faction_id, name, ticker].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
