=begin
#EVE Stable Infrastructure (ESI) - tranquility

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2020-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'date'
require 'time'

module ESI
  # route object
  class CharactersCharacterIdPlanetsPlanetIdGetRoutesInner < ApiModelBase
    attr_accessor :content_type_id

    attr_accessor :destination_pin_id

    attr_accessor :quantity

    attr_accessor :route_id

    attr_accessor :source_pin_id

    # list of pin ID waypoints
    attr_accessor :waypoints

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'content_type_id' => :'content_type_id',
        :'destination_pin_id' => :'destination_pin_id',
        :'quantity' => :'quantity',
        :'route_id' => :'route_id',
        :'source_pin_id' => :'source_pin_id',
        :'waypoints' => :'waypoints'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'content_type_id' => :'Integer',
        :'destination_pin_id' => :'Integer',
        :'quantity' => :'Float',
        :'route_id' => :'Integer',
        :'source_pin_id' => :'Integer',
        :'waypoints' => :'Array<Integer>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ESI::CharactersCharacterIdPlanetsPlanetIdGetRoutesInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ESI::CharactersCharacterIdPlanetsPlanetIdGetRoutesInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'content_type_id')
        self.content_type_id = attributes[:'content_type_id']
      else
        self.content_type_id = nil
      end

      if attributes.key?(:'destination_pin_id')
        self.destination_pin_id = attributes[:'destination_pin_id']
      else
        self.destination_pin_id = nil
      end

      if attributes.key?(:'quantity')
        self.quantity = attributes[:'quantity']
      else
        self.quantity = nil
      end

      if attributes.key?(:'route_id')
        self.route_id = attributes[:'route_id']
      else
        self.route_id = nil
      end

      if attributes.key?(:'source_pin_id')
        self.source_pin_id = attributes[:'source_pin_id']
      else
        self.source_pin_id = nil
      end

      if attributes.key?(:'waypoints')
        if (value = attributes[:'waypoints']).is_a?(Array)
          self.waypoints = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @content_type_id.nil?
        invalid_properties.push('invalid value for "content_type_id", content_type_id cannot be nil.')
      end

      if @destination_pin_id.nil?
        invalid_properties.push('invalid value for "destination_pin_id", destination_pin_id cannot be nil.')
      end

      if @quantity.nil?
        invalid_properties.push('invalid value for "quantity", quantity cannot be nil.')
      end

      if @route_id.nil?
        invalid_properties.push('invalid value for "route_id", route_id cannot be nil.')
      end

      if @source_pin_id.nil?
        invalid_properties.push('invalid value for "source_pin_id", source_pin_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @content_type_id.nil?
      return false if @destination_pin_id.nil?
      return false if @quantity.nil?
      return false if @route_id.nil?
      return false if @source_pin_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] content_type_id Value to be assigned
    def content_type_id=(content_type_id)
      if content_type_id.nil?
        fail ArgumentError, 'content_type_id cannot be nil'
      end

      @content_type_id = content_type_id
    end

    # Custom attribute writer method with validation
    # @param [Object] destination_pin_id Value to be assigned
    def destination_pin_id=(destination_pin_id)
      if destination_pin_id.nil?
        fail ArgumentError, 'destination_pin_id cannot be nil'
      end

      @destination_pin_id = destination_pin_id
    end

    # Custom attribute writer method with validation
    # @param [Object] quantity Value to be assigned
    def quantity=(quantity)
      if quantity.nil?
        fail ArgumentError, 'quantity cannot be nil'
      end

      @quantity = quantity
    end

    # Custom attribute writer method with validation
    # @param [Object] route_id Value to be assigned
    def route_id=(route_id)
      if route_id.nil?
        fail ArgumentError, 'route_id cannot be nil'
      end

      @route_id = route_id
    end

    # Custom attribute writer method with validation
    # @param [Object] source_pin_id Value to be assigned
    def source_pin_id=(source_pin_id)
      if source_pin_id.nil?
        fail ArgumentError, 'source_pin_id cannot be nil'
      end

      @source_pin_id = source_pin_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          content_type_id == o.content_type_id &&
          destination_pin_id == o.destination_pin_id &&
          quantity == o.quantity &&
          route_id == o.route_id &&
          source_pin_id == o.source_pin_id &&
          waypoints == o.waypoints
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [content_type_id, destination_pin_id, quantity, route_id, source_pin_id, waypoints].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
