=begin
#EVE Stable Infrastructure (ESI) - tranquility

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2020-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'date'
require 'time'

module ESI
  class CharactersCharacterIdGet < ApiModelBase
    # The character's alliance ID
    attr_accessor :alliance_id

    # Creation date of the character
    attr_accessor :birthday

    attr_accessor :bloodline_id

    # The character's corporation ID
    attr_accessor :corporation_id

    attr_accessor :description

    # ID of the faction the character is fighting for, if the character is enlisted in Factional Warfare
    attr_accessor :faction_id

    attr_accessor :gender

    attr_accessor :name

    attr_accessor :race_id

    attr_accessor :security_status

    # The individual title of the character
    attr_accessor :title

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'alliance_id' => :'alliance_id',
        :'birthday' => :'birthday',
        :'bloodline_id' => :'bloodline_id',
        :'corporation_id' => :'corporation_id',
        :'description' => :'description',
        :'faction_id' => :'faction_id',
        :'gender' => :'gender',
        :'name' => :'name',
        :'race_id' => :'race_id',
        :'security_status' => :'security_status',
        :'title' => :'title'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'alliance_id' => :'Integer',
        :'birthday' => :'Time',
        :'bloodline_id' => :'Integer',
        :'corporation_id' => :'Integer',
        :'description' => :'String',
        :'faction_id' => :'Integer',
        :'gender' => :'String',
        :'name' => :'String',
        :'race_id' => :'Integer',
        :'security_status' => :'Float',
        :'title' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ESI::CharactersCharacterIdGet` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ESI::CharactersCharacterIdGet`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'alliance_id')
        self.alliance_id = attributes[:'alliance_id']
      end

      if attributes.key?(:'birthday')
        self.birthday = attributes[:'birthday']
      else
        self.birthday = nil
      end

      if attributes.key?(:'bloodline_id')
        self.bloodline_id = attributes[:'bloodline_id']
      else
        self.bloodline_id = nil
      end

      if attributes.key?(:'corporation_id')
        self.corporation_id = attributes[:'corporation_id']
      else
        self.corporation_id = nil
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'faction_id')
        self.faction_id = attributes[:'faction_id']
      end

      if attributes.key?(:'gender')
        self.gender = attributes[:'gender']
      else
        self.gender = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'race_id')
        self.race_id = attributes[:'race_id']
      else
        self.race_id = nil
      end

      if attributes.key?(:'security_status')
        self.security_status = attributes[:'security_status']
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @birthday.nil?
        invalid_properties.push('invalid value for "birthday", birthday cannot be nil.')
      end

      if @bloodline_id.nil?
        invalid_properties.push('invalid value for "bloodline_id", bloodline_id cannot be nil.')
      end

      if @corporation_id.nil?
        invalid_properties.push('invalid value for "corporation_id", corporation_id cannot be nil.')
      end

      if @gender.nil?
        invalid_properties.push('invalid value for "gender", gender cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @race_id.nil?
        invalid_properties.push('invalid value for "race_id", race_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @birthday.nil?
      return false if @bloodline_id.nil?
      return false if @corporation_id.nil?
      return false if @gender.nil?
      gender_validator = EnumAttributeValidator.new('String', ["female", "male"])
      return false unless gender_validator.valid?(@gender)
      return false if @name.nil?
      return false if @race_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] birthday Value to be assigned
    def birthday=(birthday)
      if birthday.nil?
        fail ArgumentError, 'birthday cannot be nil'
      end

      @birthday = birthday
    end

    # Custom attribute writer method with validation
    # @param [Object] bloodline_id Value to be assigned
    def bloodline_id=(bloodline_id)
      if bloodline_id.nil?
        fail ArgumentError, 'bloodline_id cannot be nil'
      end

      @bloodline_id = bloodline_id
    end

    # Custom attribute writer method with validation
    # @param [Object] corporation_id Value to be assigned
    def corporation_id=(corporation_id)
      if corporation_id.nil?
        fail ArgumentError, 'corporation_id cannot be nil'
      end

      @corporation_id = corporation_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] gender Object to be assigned
    def gender=(gender)
      validator = EnumAttributeValidator.new('String', ["female", "male"])
      unless validator.valid?(gender)
        fail ArgumentError, "invalid value for \"gender\", must be one of #{validator.allowable_values}."
      end
      @gender = gender
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] race_id Value to be assigned
    def race_id=(race_id)
      if race_id.nil?
        fail ArgumentError, 'race_id cannot be nil'
      end

      @race_id = race_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          alliance_id == o.alliance_id &&
          birthday == o.birthday &&
          bloodline_id == o.bloodline_id &&
          corporation_id == o.corporation_id &&
          description == o.description &&
          faction_id == o.faction_id &&
          gender == o.gender &&
          name == o.name &&
          race_id == o.race_id &&
          security_status == o.security_status &&
          title == o.title
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [alliance_id, birthday, bloodline_id, corporation_id, description, faction_id, gender, name, race_id, security_status, title].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
