=begin
#EVE Stable Infrastructure (ESI) - tranquility

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2020-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'date'
require 'time'

module ESI
  class CorporationsCorporationIdOrdersHistoryGetInner < ApiModelBase
    # Number of days the order was valid for (starting from the issued date). An order expires at time issued + duration
    attr_accessor :duration

    # For buy orders, the amount of ISK in escrow
    attr_accessor :escrow

    # True if the order is a bid (buy) order
    attr_accessor :is_buy_order

    # Date and time when this order was issued
    attr_accessor :issued

    # The character who issued this order
    attr_accessor :issued_by

    # ID of the location where order was placed
    attr_accessor :location_id

    # For buy orders, the minimum quantity that will be accepted in a matching sell order
    attr_accessor :min_volume

    # Unique order ID
    attr_accessor :order_id

    # Cost per unit for this order
    attr_accessor :price

    # Valid order range, numbers are ranges in jumps
    attr_accessor :range

    # ID of the region where order was placed
    attr_accessor :region_id

    # Current order state
    attr_accessor :state

    # The type ID of the item transacted in this order
    attr_accessor :type_id

    # Quantity of items still required or offered
    attr_accessor :volume_remain

    # Quantity of items required or offered at time order was placed
    attr_accessor :volume_total

    # The corporation wallet division used for this order
    attr_accessor :wallet_division

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'duration' => :'duration',
        :'escrow' => :'escrow',
        :'is_buy_order' => :'is_buy_order',
        :'issued' => :'issued',
        :'issued_by' => :'issued_by',
        :'location_id' => :'location_id',
        :'min_volume' => :'min_volume',
        :'order_id' => :'order_id',
        :'price' => :'price',
        :'range' => :'range',
        :'region_id' => :'region_id',
        :'state' => :'state',
        :'type_id' => :'type_id',
        :'volume_remain' => :'volume_remain',
        :'volume_total' => :'volume_total',
        :'wallet_division' => :'wallet_division'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'duration' => :'Integer',
        :'escrow' => :'Float',
        :'is_buy_order' => :'Boolean',
        :'issued' => :'Time',
        :'issued_by' => :'Integer',
        :'location_id' => :'Integer',
        :'min_volume' => :'Integer',
        :'order_id' => :'Integer',
        :'price' => :'Float',
        :'range' => :'String',
        :'region_id' => :'Integer',
        :'state' => :'String',
        :'type_id' => :'Integer',
        :'volume_remain' => :'Integer',
        :'volume_total' => :'Integer',
        :'wallet_division' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ESI::CorporationsCorporationIdOrdersHistoryGetInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ESI::CorporationsCorporationIdOrdersHistoryGetInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'duration')
        self.duration = attributes[:'duration']
      else
        self.duration = nil
      end

      if attributes.key?(:'escrow')
        self.escrow = attributes[:'escrow']
      end

      if attributes.key?(:'is_buy_order')
        self.is_buy_order = attributes[:'is_buy_order']
      end

      if attributes.key?(:'issued')
        self.issued = attributes[:'issued']
      else
        self.issued = nil
      end

      if attributes.key?(:'issued_by')
        self.issued_by = attributes[:'issued_by']
      end

      if attributes.key?(:'location_id')
        self.location_id = attributes[:'location_id']
      else
        self.location_id = nil
      end

      if attributes.key?(:'min_volume')
        self.min_volume = attributes[:'min_volume']
      end

      if attributes.key?(:'order_id')
        self.order_id = attributes[:'order_id']
      else
        self.order_id = nil
      end

      if attributes.key?(:'price')
        self.price = attributes[:'price']
      else
        self.price = nil
      end

      if attributes.key?(:'range')
        self.range = attributes[:'range']
      else
        self.range = nil
      end

      if attributes.key?(:'region_id')
        self.region_id = attributes[:'region_id']
      else
        self.region_id = nil
      end

      if attributes.key?(:'state')
        self.state = attributes[:'state']
      else
        self.state = nil
      end

      if attributes.key?(:'type_id')
        self.type_id = attributes[:'type_id']
      else
        self.type_id = nil
      end

      if attributes.key?(:'volume_remain')
        self.volume_remain = attributes[:'volume_remain']
      else
        self.volume_remain = nil
      end

      if attributes.key?(:'volume_total')
        self.volume_total = attributes[:'volume_total']
      else
        self.volume_total = nil
      end

      if attributes.key?(:'wallet_division')
        self.wallet_division = attributes[:'wallet_division']
      else
        self.wallet_division = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @duration.nil?
        invalid_properties.push('invalid value for "duration", duration cannot be nil.')
      end

      if @issued.nil?
        invalid_properties.push('invalid value for "issued", issued cannot be nil.')
      end

      if @location_id.nil?
        invalid_properties.push('invalid value for "location_id", location_id cannot be nil.')
      end

      if @order_id.nil?
        invalid_properties.push('invalid value for "order_id", order_id cannot be nil.')
      end

      if @price.nil?
        invalid_properties.push('invalid value for "price", price cannot be nil.')
      end

      if @range.nil?
        invalid_properties.push('invalid value for "range", range cannot be nil.')
      end

      if @region_id.nil?
        invalid_properties.push('invalid value for "region_id", region_id cannot be nil.')
      end

      if @state.nil?
        invalid_properties.push('invalid value for "state", state cannot be nil.')
      end

      if @type_id.nil?
        invalid_properties.push('invalid value for "type_id", type_id cannot be nil.')
      end

      if @volume_remain.nil?
        invalid_properties.push('invalid value for "volume_remain", volume_remain cannot be nil.')
      end

      if @volume_total.nil?
        invalid_properties.push('invalid value for "volume_total", volume_total cannot be nil.')
      end

      if @wallet_division.nil?
        invalid_properties.push('invalid value for "wallet_division", wallet_division cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @duration.nil?
      return false if @issued.nil?
      return false if @location_id.nil?
      return false if @order_id.nil?
      return false if @price.nil?
      return false if @range.nil?
      range_validator = EnumAttributeValidator.new('String', ["1", "10", "2", "20", "3", "30", "4", "40", "5", "region", "solarsystem", "station"])
      return false unless range_validator.valid?(@range)
      return false if @region_id.nil?
      return false if @state.nil?
      state_validator = EnumAttributeValidator.new('String', ["cancelled", "expired"])
      return false unless state_validator.valid?(@state)
      return false if @type_id.nil?
      return false if @volume_remain.nil?
      return false if @volume_total.nil?
      return false if @wallet_division.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] duration Value to be assigned
    def duration=(duration)
      if duration.nil?
        fail ArgumentError, 'duration cannot be nil'
      end

      @duration = duration
    end

    # Custom attribute writer method with validation
    # @param [Object] issued Value to be assigned
    def issued=(issued)
      if issued.nil?
        fail ArgumentError, 'issued cannot be nil'
      end

      @issued = issued
    end

    # Custom attribute writer method with validation
    # @param [Object] location_id Value to be assigned
    def location_id=(location_id)
      if location_id.nil?
        fail ArgumentError, 'location_id cannot be nil'
      end

      @location_id = location_id
    end

    # Custom attribute writer method with validation
    # @param [Object] order_id Value to be assigned
    def order_id=(order_id)
      if order_id.nil?
        fail ArgumentError, 'order_id cannot be nil'
      end

      @order_id = order_id
    end

    # Custom attribute writer method with validation
    # @param [Object] price Value to be assigned
    def price=(price)
      if price.nil?
        fail ArgumentError, 'price cannot be nil'
      end

      @price = price
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] range Object to be assigned
    def range=(range)
      validator = EnumAttributeValidator.new('String', ["1", "10", "2", "20", "3", "30", "4", "40", "5", "region", "solarsystem", "station"])
      unless validator.valid?(range)
        fail ArgumentError, "invalid value for \"range\", must be one of #{validator.allowable_values}."
      end
      @range = range
    end

    # Custom attribute writer method with validation
    # @param [Object] region_id Value to be assigned
    def region_id=(region_id)
      if region_id.nil?
        fail ArgumentError, 'region_id cannot be nil'
      end

      @region_id = region_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] state Object to be assigned
    def state=(state)
      validator = EnumAttributeValidator.new('String', ["cancelled", "expired"])
      unless validator.valid?(state)
        fail ArgumentError, "invalid value for \"state\", must be one of #{validator.allowable_values}."
      end
      @state = state
    end

    # Custom attribute writer method with validation
    # @param [Object] type_id Value to be assigned
    def type_id=(type_id)
      if type_id.nil?
        fail ArgumentError, 'type_id cannot be nil'
      end

      @type_id = type_id
    end

    # Custom attribute writer method with validation
    # @param [Object] volume_remain Value to be assigned
    def volume_remain=(volume_remain)
      if volume_remain.nil?
        fail ArgumentError, 'volume_remain cannot be nil'
      end

      @volume_remain = volume_remain
    end

    # Custom attribute writer method with validation
    # @param [Object] volume_total Value to be assigned
    def volume_total=(volume_total)
      if volume_total.nil?
        fail ArgumentError, 'volume_total cannot be nil'
      end

      @volume_total = volume_total
    end

    # Custom attribute writer method with validation
    # @param [Object] wallet_division Value to be assigned
    def wallet_division=(wallet_division)
      if wallet_division.nil?
        fail ArgumentError, 'wallet_division cannot be nil'
      end

      @wallet_division = wallet_division
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          duration == o.duration &&
          escrow == o.escrow &&
          is_buy_order == o.is_buy_order &&
          issued == o.issued &&
          issued_by == o.issued_by &&
          location_id == o.location_id &&
          min_volume == o.min_volume &&
          order_id == o.order_id &&
          price == o.price &&
          range == o.range &&
          region_id == o.region_id &&
          state == o.state &&
          type_id == o.type_id &&
          volume_remain == o.volume_remain &&
          volume_total == o.volume_total &&
          wallet_division == o.wallet_division
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [duration, escrow, is_buy_order, issued, issued_by, location_id, min_volume, order_id, price, range, region_id, state, type_id, volume_remain, volume_total, wallet_division].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
