=begin
#EVE Stable Infrastructure (ESI) - tranquility

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2020-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'date'
require 'time'

module ESI
  class DogmaDynamicItemsTypeIdItemIdGet < ApiModelBase
    # The ID of the character who created the item
    attr_accessor :created_by

    attr_accessor :dogma_attributes

    attr_accessor :dogma_effects

    # The type ID of the mutator used to generate the dynamic item.
    attr_accessor :mutator_type_id

    # The type ID of the source item the mutator was applied to create the dynamic item.
    attr_accessor :source_type_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'created_by' => :'created_by',
        :'dogma_attributes' => :'dogma_attributes',
        :'dogma_effects' => :'dogma_effects',
        :'mutator_type_id' => :'mutator_type_id',
        :'source_type_id' => :'source_type_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'created_by' => :'Integer',
        :'dogma_attributes' => :'Array<DogmaDynamicItemsTypeIdItemIdGetDogmaAttributesInner>',
        :'dogma_effects' => :'Array<DogmaDynamicItemsTypeIdItemIdGetDogmaEffectsInner>',
        :'mutator_type_id' => :'Integer',
        :'source_type_id' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ESI::DogmaDynamicItemsTypeIdItemIdGet` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ESI::DogmaDynamicItemsTypeIdItemIdGet`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'created_by')
        self.created_by = attributes[:'created_by']
      else
        self.created_by = nil
      end

      if attributes.key?(:'dogma_attributes')
        if (value = attributes[:'dogma_attributes']).is_a?(Array)
          self.dogma_attributes = value
        end
      else
        self.dogma_attributes = nil
      end

      if attributes.key?(:'dogma_effects')
        if (value = attributes[:'dogma_effects']).is_a?(Array)
          self.dogma_effects = value
        end
      else
        self.dogma_effects = nil
      end

      if attributes.key?(:'mutator_type_id')
        self.mutator_type_id = attributes[:'mutator_type_id']
      else
        self.mutator_type_id = nil
      end

      if attributes.key?(:'source_type_id')
        self.source_type_id = attributes[:'source_type_id']
      else
        self.source_type_id = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @created_by.nil?
        invalid_properties.push('invalid value for "created_by", created_by cannot be nil.')
      end

      if @dogma_attributes.nil?
        invalid_properties.push('invalid value for "dogma_attributes", dogma_attributes cannot be nil.')
      end

      if @dogma_effects.nil?
        invalid_properties.push('invalid value for "dogma_effects", dogma_effects cannot be nil.')
      end

      if @mutator_type_id.nil?
        invalid_properties.push('invalid value for "mutator_type_id", mutator_type_id cannot be nil.')
      end

      if @source_type_id.nil?
        invalid_properties.push('invalid value for "source_type_id", source_type_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @created_by.nil?
      return false if @dogma_attributes.nil?
      return false if @dogma_effects.nil?
      return false if @mutator_type_id.nil?
      return false if @source_type_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] created_by Value to be assigned
    def created_by=(created_by)
      if created_by.nil?
        fail ArgumentError, 'created_by cannot be nil'
      end

      @created_by = created_by
    end

    # Custom attribute writer method with validation
    # @param [Object] dogma_attributes Value to be assigned
    def dogma_attributes=(dogma_attributes)
      if dogma_attributes.nil?
        fail ArgumentError, 'dogma_attributes cannot be nil'
      end

      @dogma_attributes = dogma_attributes
    end

    # Custom attribute writer method with validation
    # @param [Object] dogma_effects Value to be assigned
    def dogma_effects=(dogma_effects)
      if dogma_effects.nil?
        fail ArgumentError, 'dogma_effects cannot be nil'
      end

      @dogma_effects = dogma_effects
    end

    # Custom attribute writer method with validation
    # @param [Object] mutator_type_id Value to be assigned
    def mutator_type_id=(mutator_type_id)
      if mutator_type_id.nil?
        fail ArgumentError, 'mutator_type_id cannot be nil'
      end

      @mutator_type_id = mutator_type_id
    end

    # Custom attribute writer method with validation
    # @param [Object] source_type_id Value to be assigned
    def source_type_id=(source_type_id)
      if source_type_id.nil?
        fail ArgumentError, 'source_type_id cannot be nil'
      end

      @source_type_id = source_type_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          created_by == o.created_by &&
          dogma_attributes == o.dogma_attributes &&
          dogma_effects == o.dogma_effects &&
          mutator_type_id == o.mutator_type_id &&
          source_type_id == o.source_type_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [created_by, dogma_attributes, dogma_effects, mutator_type_id, source_type_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
