=begin
#EVE Stable Infrastructure (ESI) - tranquility

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2020-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'date'
require 'time'

module ESI
  class KillmailsKillmailIdKillmailHashGet < ApiModelBase
    attr_accessor :attackers

    # ID of the killmail
    attr_accessor :killmail_id

    # Time that the victim was killed and the killmail generated 
    attr_accessor :killmail_time

    # Moon if the kill took place at one
    attr_accessor :moon_id

    # Solar system that the kill took place in 
    attr_accessor :solar_system_id

    attr_accessor :victim

    # War if the killmail is generated in relation to an official war 
    attr_accessor :war_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'attackers' => :'attackers',
        :'killmail_id' => :'killmail_id',
        :'killmail_time' => :'killmail_time',
        :'moon_id' => :'moon_id',
        :'solar_system_id' => :'solar_system_id',
        :'victim' => :'victim',
        :'war_id' => :'war_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'attackers' => :'Array<KillmailsKillmailIdKillmailHashGetAttackersInner>',
        :'killmail_id' => :'Integer',
        :'killmail_time' => :'Time',
        :'moon_id' => :'Integer',
        :'solar_system_id' => :'Integer',
        :'victim' => :'KillmailsKillmailIdKillmailHashGetVictim',
        :'war_id' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ESI::KillmailsKillmailIdKillmailHashGet` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ESI::KillmailsKillmailIdKillmailHashGet`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'attackers')
        if (value = attributes[:'attackers']).is_a?(Array)
          self.attackers = value
        end
      else
        self.attackers = nil
      end

      if attributes.key?(:'killmail_id')
        self.killmail_id = attributes[:'killmail_id']
      else
        self.killmail_id = nil
      end

      if attributes.key?(:'killmail_time')
        self.killmail_time = attributes[:'killmail_time']
      else
        self.killmail_time = nil
      end

      if attributes.key?(:'moon_id')
        self.moon_id = attributes[:'moon_id']
      end

      if attributes.key?(:'solar_system_id')
        self.solar_system_id = attributes[:'solar_system_id']
      else
        self.solar_system_id = nil
      end

      if attributes.key?(:'victim')
        self.victim = attributes[:'victim']
      else
        self.victim = nil
      end

      if attributes.key?(:'war_id')
        self.war_id = attributes[:'war_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @attackers.nil?
        invalid_properties.push('invalid value for "attackers", attackers cannot be nil.')
      end

      if @killmail_id.nil?
        invalid_properties.push('invalid value for "killmail_id", killmail_id cannot be nil.')
      end

      if @killmail_time.nil?
        invalid_properties.push('invalid value for "killmail_time", killmail_time cannot be nil.')
      end

      if @solar_system_id.nil?
        invalid_properties.push('invalid value for "solar_system_id", solar_system_id cannot be nil.')
      end

      if @victim.nil?
        invalid_properties.push('invalid value for "victim", victim cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @attackers.nil?
      return false if @killmail_id.nil?
      return false if @killmail_time.nil?
      return false if @solar_system_id.nil?
      return false if @victim.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] attackers Value to be assigned
    def attackers=(attackers)
      if attackers.nil?
        fail ArgumentError, 'attackers cannot be nil'
      end

      @attackers = attackers
    end

    # Custom attribute writer method with validation
    # @param [Object] killmail_id Value to be assigned
    def killmail_id=(killmail_id)
      if killmail_id.nil?
        fail ArgumentError, 'killmail_id cannot be nil'
      end

      @killmail_id = killmail_id
    end

    # Custom attribute writer method with validation
    # @param [Object] killmail_time Value to be assigned
    def killmail_time=(killmail_time)
      if killmail_time.nil?
        fail ArgumentError, 'killmail_time cannot be nil'
      end

      @killmail_time = killmail_time
    end

    # Custom attribute writer method with validation
    # @param [Object] solar_system_id Value to be assigned
    def solar_system_id=(solar_system_id)
      if solar_system_id.nil?
        fail ArgumentError, 'solar_system_id cannot be nil'
      end

      @solar_system_id = solar_system_id
    end

    # Custom attribute writer method with validation
    # @param [Object] victim Value to be assigned
    def victim=(victim)
      if victim.nil?
        fail ArgumentError, 'victim cannot be nil'
      end

      @victim = victim
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          attackers == o.attackers &&
          killmail_id == o.killmail_id &&
          killmail_time == o.killmail_time &&
          moon_id == o.moon_id &&
          solar_system_id == o.solar_system_id &&
          victim == o.victim &&
          war_id == o.war_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [attackers, killmail_id, killmail_time, moon_id, solar_system_id, victim, war_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
