=begin
#EVE Stable Infrastructure (ESI) - tranquility

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2020-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'date'
require 'time'

module ESI
  class UniverseGraphicsGraphicIdGet < ApiModelBase
    attr_accessor :collision_file

    attr_accessor :graphic_file

    attr_accessor :graphic_id

    attr_accessor :icon_folder

    attr_accessor :sof_dna

    attr_accessor :sof_fation_name

    attr_accessor :sof_hull_name

    attr_accessor :sof_race_name

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'collision_file' => :'collision_file',
        :'graphic_file' => :'graphic_file',
        :'graphic_id' => :'graphic_id',
        :'icon_folder' => :'icon_folder',
        :'sof_dna' => :'sof_dna',
        :'sof_fation_name' => :'sof_fation_name',
        :'sof_hull_name' => :'sof_hull_name',
        :'sof_race_name' => :'sof_race_name'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'collision_file' => :'String',
        :'graphic_file' => :'String',
        :'graphic_id' => :'Integer',
        :'icon_folder' => :'String',
        :'sof_dna' => :'String',
        :'sof_fation_name' => :'String',
        :'sof_hull_name' => :'String',
        :'sof_race_name' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ESI::UniverseGraphicsGraphicIdGet` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ESI::UniverseGraphicsGraphicIdGet`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'collision_file')
        self.collision_file = attributes[:'collision_file']
      end

      if attributes.key?(:'graphic_file')
        self.graphic_file = attributes[:'graphic_file']
      end

      if attributes.key?(:'graphic_id')
        self.graphic_id = attributes[:'graphic_id']
      else
        self.graphic_id = nil
      end

      if attributes.key?(:'icon_folder')
        self.icon_folder = attributes[:'icon_folder']
      end

      if attributes.key?(:'sof_dna')
        self.sof_dna = attributes[:'sof_dna']
      end

      if attributes.key?(:'sof_fation_name')
        self.sof_fation_name = attributes[:'sof_fation_name']
      end

      if attributes.key?(:'sof_hull_name')
        self.sof_hull_name = attributes[:'sof_hull_name']
      end

      if attributes.key?(:'sof_race_name')
        self.sof_race_name = attributes[:'sof_race_name']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @graphic_id.nil?
        invalid_properties.push('invalid value for "graphic_id", graphic_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @graphic_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] graphic_id Value to be assigned
    def graphic_id=(graphic_id)
      if graphic_id.nil?
        fail ArgumentError, 'graphic_id cannot be nil'
      end

      @graphic_id = graphic_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          collision_file == o.collision_file &&
          graphic_file == o.graphic_file &&
          graphic_id == o.graphic_id &&
          icon_folder == o.icon_folder &&
          sof_dna == o.sof_dna &&
          sof_fation_name == o.sof_fation_name &&
          sof_hull_name == o.sof_hull_name &&
          sof_race_name == o.sof_race_name
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [collision_file, graphic_file, graphic_id, icon_folder, sof_dna, sof_fation_name, sof_hull_name, sof_race_name].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
