=begin
#EVE Stable Infrastructure (ESI) - tranquility

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2020-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'date'
require 'time'

module ESI
  class WarsWarIdGet < ApiModelBase
    attr_accessor :aggressor

    # allied corporations or alliances, each object contains either corporation_id or alliance_id
    attr_accessor :allies

    # Time that the war was declared
    attr_accessor :declared

    attr_accessor :defender

    # Time the war ended and shooting was no longer allowed
    attr_accessor :finished

    # ID of the specified war
    attr_accessor :id

    # Was the war declared mutual by both parties
    attr_accessor :mutual

    # Is the war currently open for allies or not
    attr_accessor :open_for_allies

    # Time the war was retracted but both sides could still shoot each other
    attr_accessor :retracted

    # Time when the war started and both sides could shoot each other
    attr_accessor :started

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'aggressor' => :'aggressor',
        :'allies' => :'allies',
        :'declared' => :'declared',
        :'defender' => :'defender',
        :'finished' => :'finished',
        :'id' => :'id',
        :'mutual' => :'mutual',
        :'open_for_allies' => :'open_for_allies',
        :'retracted' => :'retracted',
        :'started' => :'started'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'aggressor' => :'WarsWarIdGetAggressor',
        :'allies' => :'Array<WarsWarIdGetAlliesInner>',
        :'declared' => :'Time',
        :'defender' => :'WarsWarIdGetDefender',
        :'finished' => :'Time',
        :'id' => :'Integer',
        :'mutual' => :'Boolean',
        :'open_for_allies' => :'Boolean',
        :'retracted' => :'Time',
        :'started' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ESI::WarsWarIdGet` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ESI::WarsWarIdGet`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'aggressor')
        self.aggressor = attributes[:'aggressor']
      else
        self.aggressor = nil
      end

      if attributes.key?(:'allies')
        if (value = attributes[:'allies']).is_a?(Array)
          self.allies = value
        end
      end

      if attributes.key?(:'declared')
        self.declared = attributes[:'declared']
      else
        self.declared = nil
      end

      if attributes.key?(:'defender')
        self.defender = attributes[:'defender']
      else
        self.defender = nil
      end

      if attributes.key?(:'finished')
        self.finished = attributes[:'finished']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'mutual')
        self.mutual = attributes[:'mutual']
      else
        self.mutual = nil
      end

      if attributes.key?(:'open_for_allies')
        self.open_for_allies = attributes[:'open_for_allies']
      else
        self.open_for_allies = nil
      end

      if attributes.key?(:'retracted')
        self.retracted = attributes[:'retracted']
      end

      if attributes.key?(:'started')
        self.started = attributes[:'started']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @aggressor.nil?
        invalid_properties.push('invalid value for "aggressor", aggressor cannot be nil.')
      end

      if @declared.nil?
        invalid_properties.push('invalid value for "declared", declared cannot be nil.')
      end

      if @defender.nil?
        invalid_properties.push('invalid value for "defender", defender cannot be nil.')
      end

      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @mutual.nil?
        invalid_properties.push('invalid value for "mutual", mutual cannot be nil.')
      end

      if @open_for_allies.nil?
        invalid_properties.push('invalid value for "open_for_allies", open_for_allies cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @aggressor.nil?
      return false if @declared.nil?
      return false if @defender.nil?
      return false if @id.nil?
      return false if @mutual.nil?
      return false if @open_for_allies.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] aggressor Value to be assigned
    def aggressor=(aggressor)
      if aggressor.nil?
        fail ArgumentError, 'aggressor cannot be nil'
      end

      @aggressor = aggressor
    end

    # Custom attribute writer method with validation
    # @param [Object] declared Value to be assigned
    def declared=(declared)
      if declared.nil?
        fail ArgumentError, 'declared cannot be nil'
      end

      @declared = declared
    end

    # Custom attribute writer method with validation
    # @param [Object] defender Value to be assigned
    def defender=(defender)
      if defender.nil?
        fail ArgumentError, 'defender cannot be nil'
      end

      @defender = defender
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] mutual Value to be assigned
    def mutual=(mutual)
      if mutual.nil?
        fail ArgumentError, 'mutual cannot be nil'
      end

      @mutual = mutual
    end

    # Custom attribute writer method with validation
    # @param [Object] open_for_allies Value to be assigned
    def open_for_allies=(open_for_allies)
      if open_for_allies.nil?
        fail ArgumentError, 'open_for_allies cannot be nil'
      end

      @open_for_allies = open_for_allies
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          aggressor == o.aggressor &&
          allies == o.allies &&
          declared == o.declared &&
          defender == o.defender &&
          finished == o.finished &&
          id == o.id &&
          mutual == o.mutual &&
          open_for_allies == o.open_for_allies &&
          retracted == o.retracted &&
          started == o.started
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [aggressor, allies, declared, defender, finished, id, mutual, open_for_allies, retracted, started].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
