=begin
#EVE Stable Infrastructure (ESI) - tranquility

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2020-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'cgi'

module ESI
  class AllianceApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # List all alliances
    # List all active player alliances
    # @param x_compatibility_date [Date] The compatibility date for the request.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :accept_language The language to use for the response. (default to 'en')
    # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
    # @option opts [String] :x_tenant The tenant ID for the request. (default to 'tranquility')
    # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
    # @return [Array<Integer>]
    def get_alliances(x_compatibility_date, opts = {})
      data, _status_code, _headers = get_alliances_with_http_info(x_compatibility_date, opts)
      data
    end

    # List all alliances
    # List all active player alliances
    # @param x_compatibility_date [Date] The compatibility date for the request.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :accept_language The language to use for the response. (default to 'en')
    # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
    # @option opts [String] :x_tenant The tenant ID for the request. (default to 'tranquility')
    # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
    # @return [Array<(Array<Integer>, Integer, Hash)>] Array<Integer> data, response status code and response headers
    def get_alliances_with_http_info(x_compatibility_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AllianceApi.get_alliances ...'
      end
      # verify the required parameter 'x_compatibility_date' is set
      if @api_client.config.client_side_validation && x_compatibility_date.nil?
        fail ArgumentError, "Missing the required parameter 'x_compatibility_date' when calling AllianceApi.get_alliances"
      end
      # verify enum value
      allowable_values = ["2020-01-01"]
      if @api_client.config.client_side_validation && !allowable_values.include?(x_compatibility_date)
        fail ArgumentError, "invalid value for \"x_compatibility_date\", must be one of #{allowable_values}"
      end
      allowable_values = ["en", "de", "fr", "ja", "ru", "zh", "ko", "es"]
      if @api_client.config.client_side_validation && opts[:'accept_language'] && !allowable_values.include?(opts[:'accept_language'])
        fail ArgumentError, "invalid value for \"accept_language\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/alliances'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Compatibility-Date'] = x_compatibility_date
      header_params[:'Accept-Language'] = opts[:'accept_language'] if !opts[:'accept_language'].nil?
      header_params[:'If-None-Match'] = opts[:'if_none_match'] if !opts[:'if_none_match'].nil?
      header_params[:'X-Tenant'] = opts[:'x_tenant'] if !opts[:'x_tenant'].nil?
      header_params[:'If-Modified-Since'] = opts[:'if_modified_since'] if !opts[:'if_modified_since'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Array<Integer>'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"AllianceApi.get_alliances",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AllianceApi#get_alliances\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get alliance information
    # Public information about an alliance
    # @param alliance_id [Integer] The ID of the alliance
    # @param x_compatibility_date [Date] The compatibility date for the request.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :accept_language The language to use for the response. (default to 'en')
    # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
    # @option opts [String] :x_tenant The tenant ID for the request. (default to 'tranquility')
    # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
    # @return [AlliancesAllianceIdGet]
    def get_alliances_alliance_id(alliance_id, x_compatibility_date, opts = {})
      data, _status_code, _headers = get_alliances_alliance_id_with_http_info(alliance_id, x_compatibility_date, opts)
      data
    end

    # Get alliance information
    # Public information about an alliance
    # @param alliance_id [Integer] The ID of the alliance
    # @param x_compatibility_date [Date] The compatibility date for the request.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :accept_language The language to use for the response. (default to 'en')
    # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
    # @option opts [String] :x_tenant The tenant ID for the request. (default to 'tranquility')
    # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
    # @return [Array<(AlliancesAllianceIdGet, Integer, Hash)>] AlliancesAllianceIdGet data, response status code and response headers
    def get_alliances_alliance_id_with_http_info(alliance_id, x_compatibility_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AllianceApi.get_alliances_alliance_id ...'
      end
      # verify the required parameter 'alliance_id' is set
      if @api_client.config.client_side_validation && alliance_id.nil?
        fail ArgumentError, "Missing the required parameter 'alliance_id' when calling AllianceApi.get_alliances_alliance_id"
      end
      # verify the required parameter 'x_compatibility_date' is set
      if @api_client.config.client_side_validation && x_compatibility_date.nil?
        fail ArgumentError, "Missing the required parameter 'x_compatibility_date' when calling AllianceApi.get_alliances_alliance_id"
      end
      # verify enum value
      allowable_values = ["2020-01-01"]
      if @api_client.config.client_side_validation && !allowable_values.include?(x_compatibility_date)
        fail ArgumentError, "invalid value for \"x_compatibility_date\", must be one of #{allowable_values}"
      end
      allowable_values = ["en", "de", "fr", "ja", "ru", "zh", "ko", "es"]
      if @api_client.config.client_side_validation && opts[:'accept_language'] && !allowable_values.include?(opts[:'accept_language'])
        fail ArgumentError, "invalid value for \"accept_language\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/alliances/{alliance_id}'.sub('{' + 'alliance_id' + '}', CGI.escape(alliance_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Compatibility-Date'] = x_compatibility_date
      header_params[:'Accept-Language'] = opts[:'accept_language'] if !opts[:'accept_language'].nil?
      header_params[:'If-None-Match'] = opts[:'if_none_match'] if !opts[:'if_none_match'].nil?
      header_params[:'X-Tenant'] = opts[:'x_tenant'] if !opts[:'x_tenant'].nil?
      header_params[:'If-Modified-Since'] = opts[:'if_modified_since'] if !opts[:'if_modified_since'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'AlliancesAllianceIdGet'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"AllianceApi.get_alliances_alliance_id",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AllianceApi#get_alliances_alliance_id\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List alliance's corporations
    # List all current member corporations of an alliance
    # @param alliance_id [Integer] The ID of the alliance
    # @param x_compatibility_date [Date] The compatibility date for the request.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :accept_language The language to use for the response. (default to 'en')
    # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
    # @option opts [String] :x_tenant The tenant ID for the request. (default to 'tranquility')
    # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
    # @return [Array<Integer>]
    def get_alliances_alliance_id_corporations(alliance_id, x_compatibility_date, opts = {})
      data, _status_code, _headers = get_alliances_alliance_id_corporations_with_http_info(alliance_id, x_compatibility_date, opts)
      data
    end

    # List alliance&#39;s corporations
    # List all current member corporations of an alliance
    # @param alliance_id [Integer] The ID of the alliance
    # @param x_compatibility_date [Date] The compatibility date for the request.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :accept_language The language to use for the response. (default to 'en')
    # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
    # @option opts [String] :x_tenant The tenant ID for the request. (default to 'tranquility')
    # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
    # @return [Array<(Array<Integer>, Integer, Hash)>] Array<Integer> data, response status code and response headers
    def get_alliances_alliance_id_corporations_with_http_info(alliance_id, x_compatibility_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AllianceApi.get_alliances_alliance_id_corporations ...'
      end
      # verify the required parameter 'alliance_id' is set
      if @api_client.config.client_side_validation && alliance_id.nil?
        fail ArgumentError, "Missing the required parameter 'alliance_id' when calling AllianceApi.get_alliances_alliance_id_corporations"
      end
      # verify the required parameter 'x_compatibility_date' is set
      if @api_client.config.client_side_validation && x_compatibility_date.nil?
        fail ArgumentError, "Missing the required parameter 'x_compatibility_date' when calling AllianceApi.get_alliances_alliance_id_corporations"
      end
      # verify enum value
      allowable_values = ["2020-01-01"]
      if @api_client.config.client_side_validation && !allowable_values.include?(x_compatibility_date)
        fail ArgumentError, "invalid value for \"x_compatibility_date\", must be one of #{allowable_values}"
      end
      allowable_values = ["en", "de", "fr", "ja", "ru", "zh", "ko", "es"]
      if @api_client.config.client_side_validation && opts[:'accept_language'] && !allowable_values.include?(opts[:'accept_language'])
        fail ArgumentError, "invalid value for \"accept_language\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/alliances/{alliance_id}/corporations'.sub('{' + 'alliance_id' + '}', CGI.escape(alliance_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Compatibility-Date'] = x_compatibility_date
      header_params[:'Accept-Language'] = opts[:'accept_language'] if !opts[:'accept_language'].nil?
      header_params[:'If-None-Match'] = opts[:'if_none_match'] if !opts[:'if_none_match'].nil?
      header_params[:'X-Tenant'] = opts[:'x_tenant'] if !opts[:'x_tenant'].nil?
      header_params[:'If-Modified-Since'] = opts[:'if_modified_since'] if !opts[:'if_modified_since'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Array<Integer>'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"AllianceApi.get_alliances_alliance_id_corporations",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AllianceApi#get_alliances_alliance_id_corporations\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get alliance icon
    # Get the icon urls for a alliance  This route expires daily at 11:05
    # @param alliance_id [Integer] The ID of the alliance
    # @param x_compatibility_date [Date] The compatibility date for the request.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :accept_language The language to use for the response. (default to 'en')
    # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
    # @option opts [String] :x_tenant The tenant ID for the request. (default to 'tranquility')
    # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
    # @return [AlliancesAllianceIdIconsGet]
    def get_alliances_alliance_id_icons(alliance_id, x_compatibility_date, opts = {})
      data, _status_code, _headers = get_alliances_alliance_id_icons_with_http_info(alliance_id, x_compatibility_date, opts)
      data
    end

    # Get alliance icon
    # Get the icon urls for a alliance  This route expires daily at 11:05
    # @param alliance_id [Integer] The ID of the alliance
    # @param x_compatibility_date [Date] The compatibility date for the request.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :accept_language The language to use for the response. (default to 'en')
    # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
    # @option opts [String] :x_tenant The tenant ID for the request. (default to 'tranquility')
    # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
    # @return [Array<(AlliancesAllianceIdIconsGet, Integer, Hash)>] AlliancesAllianceIdIconsGet data, response status code and response headers
    def get_alliances_alliance_id_icons_with_http_info(alliance_id, x_compatibility_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AllianceApi.get_alliances_alliance_id_icons ...'
      end
      # verify the required parameter 'alliance_id' is set
      if @api_client.config.client_side_validation && alliance_id.nil?
        fail ArgumentError, "Missing the required parameter 'alliance_id' when calling AllianceApi.get_alliances_alliance_id_icons"
      end
      # verify the required parameter 'x_compatibility_date' is set
      if @api_client.config.client_side_validation && x_compatibility_date.nil?
        fail ArgumentError, "Missing the required parameter 'x_compatibility_date' when calling AllianceApi.get_alliances_alliance_id_icons"
      end
      # verify enum value
      allowable_values = ["2020-01-01"]
      if @api_client.config.client_side_validation && !allowable_values.include?(x_compatibility_date)
        fail ArgumentError, "invalid value for \"x_compatibility_date\", must be one of #{allowable_values}"
      end
      allowable_values = ["en", "de", "fr", "ja", "ru", "zh", "ko", "es"]
      if @api_client.config.client_side_validation && opts[:'accept_language'] && !allowable_values.include?(opts[:'accept_language'])
        fail ArgumentError, "invalid value for \"accept_language\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/alliances/{alliance_id}/icons'.sub('{' + 'alliance_id' + '}', CGI.escape(alliance_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Compatibility-Date'] = x_compatibility_date
      header_params[:'Accept-Language'] = opts[:'accept_language'] if !opts[:'accept_language'].nil?
      header_params[:'If-None-Match'] = opts[:'if_none_match'] if !opts[:'if_none_match'].nil?
      header_params[:'X-Tenant'] = opts[:'x_tenant'] if !opts[:'x_tenant'].nil?
      header_params[:'If-Modified-Since'] = opts[:'if_modified_since'] if !opts[:'if_modified_since'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'AlliancesAllianceIdIconsGet'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"AllianceApi.get_alliances_alliance_id_icons",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AllianceApi#get_alliances_alliance_id_icons\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
