=begin
#EVE Stable Infrastructure (ESI) - tranquility

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2020-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'cgi'

module ESI
  class WarsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # List wars
    # Return a list of wars
    # @param x_compatibility_date [Date] The compatibility date for the request.
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :max_war_id 
    # @option opts [String] :accept_language The language to use for the response. (default to 'en')
    # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
    # @option opts [String] :x_tenant The tenant ID for the request. (default to 'tranquility')
    # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
    # @return [Array<Integer>]
    def get_wars(x_compatibility_date, opts = {})
      data, _status_code, _headers = get_wars_with_http_info(x_compatibility_date, opts)
      data
    end

    # List wars
    # Return a list of wars
    # @param x_compatibility_date [Date] The compatibility date for the request.
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :max_war_id 
    # @option opts [String] :accept_language The language to use for the response. (default to 'en')
    # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
    # @option opts [String] :x_tenant The tenant ID for the request. (default to 'tranquility')
    # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
    # @return [Array<(Array<Integer>, Integer, Hash)>] Array<Integer> data, response status code and response headers
    def get_wars_with_http_info(x_compatibility_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: WarsApi.get_wars ...'
      end
      # verify the required parameter 'x_compatibility_date' is set
      if @api_client.config.client_side_validation && x_compatibility_date.nil?
        fail ArgumentError, "Missing the required parameter 'x_compatibility_date' when calling WarsApi.get_wars"
      end
      # verify enum value
      allowable_values = ["2020-01-01"]
      if @api_client.config.client_side_validation && !allowable_values.include?(x_compatibility_date)
        fail ArgumentError, "invalid value for \"x_compatibility_date\", must be one of #{allowable_values}"
      end
      allowable_values = ["en", "de", "fr", "ja", "ru", "zh", "ko", "es"]
      if @api_client.config.client_side_validation && opts[:'accept_language'] && !allowable_values.include?(opts[:'accept_language'])
        fail ArgumentError, "invalid value for \"accept_language\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/wars'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'max_war_id'] = opts[:'max_war_id'] if !opts[:'max_war_id'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Compatibility-Date'] = x_compatibility_date
      header_params[:'Accept-Language'] = opts[:'accept_language'] if !opts[:'accept_language'].nil?
      header_params[:'If-None-Match'] = opts[:'if_none_match'] if !opts[:'if_none_match'].nil?
      header_params[:'X-Tenant'] = opts[:'x_tenant'] if !opts[:'x_tenant'].nil?
      header_params[:'If-Modified-Since'] = opts[:'if_modified_since'] if !opts[:'if_modified_since'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Array<Integer>'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"WarsApi.get_wars",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: WarsApi#get_wars\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get war information
    # Return details about a war
    # @param war_id [Integer] 
    # @param x_compatibility_date [Date] The compatibility date for the request.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :accept_language The language to use for the response. (default to 'en')
    # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
    # @option opts [String] :x_tenant The tenant ID for the request. (default to 'tranquility')
    # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
    # @return [WarsWarIdGet]
    def get_wars_war_id(war_id, x_compatibility_date, opts = {})
      data, _status_code, _headers = get_wars_war_id_with_http_info(war_id, x_compatibility_date, opts)
      data
    end

    # Get war information
    # Return details about a war
    # @param war_id [Integer] 
    # @param x_compatibility_date [Date] The compatibility date for the request.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :accept_language The language to use for the response. (default to 'en')
    # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
    # @option opts [String] :x_tenant The tenant ID for the request. (default to 'tranquility')
    # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
    # @return [Array<(WarsWarIdGet, Integer, Hash)>] WarsWarIdGet data, response status code and response headers
    def get_wars_war_id_with_http_info(war_id, x_compatibility_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: WarsApi.get_wars_war_id ...'
      end
      # verify the required parameter 'war_id' is set
      if @api_client.config.client_side_validation && war_id.nil?
        fail ArgumentError, "Missing the required parameter 'war_id' when calling WarsApi.get_wars_war_id"
      end
      # verify the required parameter 'x_compatibility_date' is set
      if @api_client.config.client_side_validation && x_compatibility_date.nil?
        fail ArgumentError, "Missing the required parameter 'x_compatibility_date' when calling WarsApi.get_wars_war_id"
      end
      # verify enum value
      allowable_values = ["2020-01-01"]
      if @api_client.config.client_side_validation && !allowable_values.include?(x_compatibility_date)
        fail ArgumentError, "invalid value for \"x_compatibility_date\", must be one of #{allowable_values}"
      end
      allowable_values = ["en", "de", "fr", "ja", "ru", "zh", "ko", "es"]
      if @api_client.config.client_side_validation && opts[:'accept_language'] && !allowable_values.include?(opts[:'accept_language'])
        fail ArgumentError, "invalid value for \"accept_language\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/wars/{war_id}'.sub('{' + 'war_id' + '}', CGI.escape(war_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Compatibility-Date'] = x_compatibility_date
      header_params[:'Accept-Language'] = opts[:'accept_language'] if !opts[:'accept_language'].nil?
      header_params[:'If-None-Match'] = opts[:'if_none_match'] if !opts[:'if_none_match'].nil?
      header_params[:'X-Tenant'] = opts[:'x_tenant'] if !opts[:'x_tenant'].nil?
      header_params[:'If-Modified-Since'] = opts[:'if_modified_since'] if !opts[:'if_modified_since'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'WarsWarIdGet'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"WarsApi.get_wars_war_id",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: WarsApi#get_wars_war_id\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List kills for a war
    # Return a list of kills related to a war
    # @param war_id [Integer] 
    # @param x_compatibility_date [Date] The compatibility date for the request.
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :page 
    # @option opts [String] :accept_language The language to use for the response. (default to 'en')
    # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
    # @option opts [String] :x_tenant The tenant ID for the request. (default to 'tranquility')
    # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
    # @return [Array<CharactersCharacterIdKillmailsRecentGetInner>]
    def get_wars_war_id_killmails(war_id, x_compatibility_date, opts = {})
      data, _status_code, _headers = get_wars_war_id_killmails_with_http_info(war_id, x_compatibility_date, opts)
      data
    end

    # List kills for a war
    # Return a list of kills related to a war
    # @param war_id [Integer] 
    # @param x_compatibility_date [Date] The compatibility date for the request.
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :page 
    # @option opts [String] :accept_language The language to use for the response. (default to 'en')
    # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
    # @option opts [String] :x_tenant The tenant ID for the request. (default to 'tranquility')
    # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
    # @return [Array<(Array<CharactersCharacterIdKillmailsRecentGetInner>, Integer, Hash)>] Array<CharactersCharacterIdKillmailsRecentGetInner> data, response status code and response headers
    def get_wars_war_id_killmails_with_http_info(war_id, x_compatibility_date, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: WarsApi.get_wars_war_id_killmails ...'
      end
      # verify the required parameter 'war_id' is set
      if @api_client.config.client_side_validation && war_id.nil?
        fail ArgumentError, "Missing the required parameter 'war_id' when calling WarsApi.get_wars_war_id_killmails"
      end
      # verify the required parameter 'x_compatibility_date' is set
      if @api_client.config.client_side_validation && x_compatibility_date.nil?
        fail ArgumentError, "Missing the required parameter 'x_compatibility_date' when calling WarsApi.get_wars_war_id_killmails"
      end
      # verify enum value
      allowable_values = ["2020-01-01"]
      if @api_client.config.client_side_validation && !allowable_values.include?(x_compatibility_date)
        fail ArgumentError, "invalid value for \"x_compatibility_date\", must be one of #{allowable_values}"
      end
      if @api_client.config.client_side_validation && !opts[:'page'].nil? && opts[:'page'] < 1
        fail ArgumentError, 'invalid value for "opts[:"page"]" when calling WarsApi.get_wars_war_id_killmails, must be greater than or equal to 1.'
      end

      allowable_values = ["en", "de", "fr", "ja", "ru", "zh", "ko", "es"]
      if @api_client.config.client_side_validation && opts[:'accept_language'] && !allowable_values.include?(opts[:'accept_language'])
        fail ArgumentError, "invalid value for \"accept_language\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/wars/{war_id}/killmails'.sub('{' + 'war_id' + '}', CGI.escape(war_id.to_s))

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'page'] = opts[:'page'] if !opts[:'page'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-Compatibility-Date'] = x_compatibility_date
      header_params[:'Accept-Language'] = opts[:'accept_language'] if !opts[:'accept_language'].nil?
      header_params[:'If-None-Match'] = opts[:'if_none_match'] if !opts[:'if_none_match'].nil?
      header_params[:'X-Tenant'] = opts[:'x_tenant'] if !opts[:'x_tenant'].nil?
      header_params[:'If-Modified-Since'] = opts[:'if_modified_since'] if !opts[:'if_modified_since'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Array<CharactersCharacterIdKillmailsRecentGetInner>'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"WarsApi.get_wars_war_id_killmails",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: WarsApi#get_wars_war_id_killmails\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
