=begin
#EVE Stable Infrastructure (ESI) - tranquility

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2020-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ESI::AllianceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AllianceApi' do
  before do
    # run before each test
    @api_instance = ESI::AllianceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllianceApi' do
    it 'should create an instance of AllianceApi' do
      expect(@api_instance).to be_instance_of(ESI::AllianceApi)
    end
  end

  # unit tests for get_alliances
  # List all alliances
  # List all active player alliances
  # @param x_compatibility_date The compatibility date for the request.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :accept_language The language to use for the response.
  # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
  # @option opts [String] :x_tenant The tenant ID for the request.
  # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
  # @return [Array<Integer>]
  describe 'get_alliances test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_alliances_alliance_id
  # Get alliance information
  # Public information about an alliance
  # @param alliance_id The ID of the alliance
  # @param x_compatibility_date The compatibility date for the request.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :accept_language The language to use for the response.
  # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
  # @option opts [String] :x_tenant The tenant ID for the request.
  # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
  # @return [AlliancesAllianceIdGet]
  describe 'get_alliances_alliance_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_alliances_alliance_id_corporations
  # List alliance&#39;s corporations
  # List all current member corporations of an alliance
  # @param alliance_id The ID of the alliance
  # @param x_compatibility_date The compatibility date for the request.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :accept_language The language to use for the response.
  # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
  # @option opts [String] :x_tenant The tenant ID for the request.
  # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
  # @return [Array<Integer>]
  describe 'get_alliances_alliance_id_corporations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_alliances_alliance_id_icons
  # Get alliance icon
  # Get the icon urls for a alliance  This route expires daily at 11:05
  # @param alliance_id The ID of the alliance
  # @param x_compatibility_date The compatibility date for the request.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :accept_language The language to use for the response.
  # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
  # @option opts [String] :x_tenant The tenant ID for the request.
  # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
  # @return [AlliancesAllianceIdIconsGet]
  describe 'get_alliances_alliance_id_icons test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
