=begin
#EVE Stable Infrastructure (ESI) - tranquility

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2020-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ESI::AssetsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AssetsApi' do
  before do
    # run before each test
    @api_instance = ESI::AssetsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AssetsApi' do
    it 'should create an instance of AssetsApi' do
      expect(@api_instance).to be_instance_of(ESI::AssetsApi)
    end
  end

  # unit tests for get_characters_character_id_assets
  # Get character assets
  # Return a list of the characters assets
  # @param character_id The ID of the character
  # @param x_compatibility_date The compatibility date for the request.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [String] :accept_language The language to use for the response.
  # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
  # @option opts [String] :x_tenant The tenant ID for the request.
  # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
  # @return [Array<CharactersCharacterIdAssetsGetInner>]
  describe 'get_characters_character_id_assets test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_corporations_corporation_id_assets
  # Get corporation assets
  # Return a list of the corporation assets
  # @param corporation_id The ID of the corporation
  # @param x_compatibility_date The compatibility date for the request.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [String] :accept_language The language to use for the response.
  # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
  # @option opts [String] :x_tenant The tenant ID for the request.
  # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
  # @return [Array<CorporationsCorporationIdAssetsGetInner>]
  describe 'get_corporations_corporation_id_assets test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_characters_character_id_assets_locations
  # Get character asset locations
  # Return locations for a set of item ids, which you can get from character assets endpoint. Coordinates for items in hangars or stations are set to (0,0,0)
  # @param character_id The ID of the character
  # @param x_compatibility_date The compatibility date for the request.
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :accept_language The language to use for the response.
  # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
  # @option opts [String] :x_tenant The tenant ID for the request.
  # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
  # @return [Array<CharactersCharacterIdAssetsLocationsPostInner>]
  describe 'post_characters_character_id_assets_locations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_characters_character_id_assets_names
  # Get character asset names
  # Return names for a set of item ids, which you can get from character assets endpoint. Typically used for items that can customize names, like containers or ships.
  # @param character_id The ID of the character
  # @param x_compatibility_date The compatibility date for the request.
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :accept_language The language to use for the response.
  # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
  # @option opts [String] :x_tenant The tenant ID for the request.
  # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
  # @return [Array<CharactersCharacterIdAssetsNamesPostInner>]
  describe 'post_characters_character_id_assets_names test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_corporations_corporation_id_assets_locations
  # Get corporation asset locations
  # Return locations for a set of item ids, which you can get from corporation assets endpoint. Coordinates for items in hangars or stations are set to (0,0,0)
  # @param corporation_id The ID of the corporation
  # @param x_compatibility_date The compatibility date for the request.
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :accept_language The language to use for the response.
  # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
  # @option opts [String] :x_tenant The tenant ID for the request.
  # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
  # @return [Array<CharactersCharacterIdAssetsLocationsPostInner>]
  describe 'post_corporations_corporation_id_assets_locations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_corporations_corporation_id_assets_names
  # Get corporation asset names
  # Return names for a set of item ids, which you can get from corporation assets endpoint. Only valid for items that can customize names, like containers or ships
  # @param corporation_id The ID of the corporation
  # @param x_compatibility_date The compatibility date for the request.
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :accept_language The language to use for the response.
  # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
  # @option opts [String] :x_tenant The tenant ID for the request.
  # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
  # @return [Array<CharactersCharacterIdAssetsNamesPostInner>]
  describe 'post_corporations_corporation_id_assets_names test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
