=begin
#EVE Stable Infrastructure (ESI) - tranquility

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2020-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ESI::CalendarApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CalendarApi' do
  before do
    # run before each test
    @api_instance = ESI::CalendarApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CalendarApi' do
    it 'should create an instance of CalendarApi' do
      expect(@api_instance).to be_instance_of(ESI::CalendarApi)
    end
  end

  # unit tests for get_characters_character_id_calendar
  # List calendar event summaries
  # Get 50 event summaries from the calendar. If no from_event ID is given, the resource will return the next 50 chronological event summaries from now. If a from_event ID is specified, it will return the next 50 chronological event summaries from after that event
  # @param character_id The ID of the character
  # @param x_compatibility_date The compatibility date for the request.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :from_event 
  # @option opts [String] :accept_language The language to use for the response.
  # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
  # @option opts [String] :x_tenant The tenant ID for the request.
  # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
  # @return [Array<CharactersCharacterIdCalendarGetInner>]
  describe 'get_characters_character_id_calendar test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_characters_character_id_calendar_event_id
  # Get an event
  # Get all the information for a specific event
  # @param character_id The ID of the character
  # @param event_id 
  # @param x_compatibility_date The compatibility date for the request.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :accept_language The language to use for the response.
  # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
  # @option opts [String] :x_tenant The tenant ID for the request.
  # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
  # @return [CharactersCharacterIdCalendarEventIdGet]
  describe 'get_characters_character_id_calendar_event_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_characters_character_id_calendar_event_id_attendees
  # Get attendees
  # Get all invited attendees for a given event
  # @param character_id The ID of the character
  # @param event_id 
  # @param x_compatibility_date The compatibility date for the request.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :accept_language The language to use for the response.
  # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
  # @option opts [String] :x_tenant The tenant ID for the request.
  # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
  # @return [Array<CharactersCharacterIdCalendarEventIdAttendeesGetInner>]
  describe 'get_characters_character_id_calendar_event_id_attendees test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for put_characters_character_id_calendar_event_id
  # Respond to an event
  # Set your response status to an event
  # @param character_id The ID of the character
  # @param event_id 
  # @param x_compatibility_date The compatibility date for the request.
  # @param put_characters_character_id_calendar_event_id_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :accept_language The language to use for the response.
  # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
  # @option opts [String] :x_tenant The tenant ID for the request.
  # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
  # @return [nil]
  describe 'put_characters_character_id_calendar_event_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
