=begin
#EVE Stable Infrastructure (ESI) - tranquility

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2020-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ESI::PlanetaryInteractionApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PlanetaryInteractionApi' do
  before do
    # run before each test
    @api_instance = ESI::PlanetaryInteractionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PlanetaryInteractionApi' do
    it 'should create an instance of PlanetaryInteractionApi' do
      expect(@api_instance).to be_instance_of(ESI::PlanetaryInteractionApi)
    end
  end

  # unit tests for get_characters_character_id_planets
  # Get colonies
  # Returns a list of all planetary colonies owned by a character.
  # @param character_id The ID of the character
  # @param x_compatibility_date The compatibility date for the request.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :accept_language The language to use for the response.
  # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
  # @option opts [String] :x_tenant The tenant ID for the request.
  # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
  # @return [Array<CharactersCharacterIdPlanetsGetInner>]
  describe 'get_characters_character_id_planets test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_characters_character_id_planets_planet_id
  # Get colony layout
  # Returns full details on the layout of a single planetary colony, including links, pins and routes. Note: Planetary information is only recalculated when the colony is viewed through the client. Information will not update until this criteria is met.
  # @param character_id The ID of the character
  # @param planet_id 
  # @param x_compatibility_date The compatibility date for the request.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :accept_language The language to use for the response.
  # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
  # @option opts [String] :x_tenant The tenant ID for the request.
  # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
  # @return [CharactersCharacterIdPlanetsPlanetIdGet]
  describe 'get_characters_character_id_planets_planet_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_corporations_corporation_id_customs_offices
  # List corporation customs offices
  # List customs offices owned by a corporation
  # @param corporation_id The ID of the corporation
  # @param x_compatibility_date The compatibility date for the request.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [String] :accept_language The language to use for the response.
  # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
  # @option opts [String] :x_tenant The tenant ID for the request.
  # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
  # @return [Array<CorporationsCorporationIdCustomsOfficesGetInner>]
  describe 'get_corporations_corporation_id_customs_offices test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_universe_schematics_schematic_id
  # Get schematic information
  # Get information on a planetary factory schematic
  # @param schematic_id 
  # @param x_compatibility_date The compatibility date for the request.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :accept_language The language to use for the response.
  # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
  # @option opts [String] :x_tenant The tenant ID for the request.
  # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
  # @return [UniverseSchematicsSchematicIdGet]
  describe 'get_universe_schematics_schematic_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
