=begin
#EVE Stable Infrastructure (ESI) - tranquility

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2020-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ESI::SkillsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SkillsApi' do
  before do
    # run before each test
    @api_instance = ESI::SkillsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SkillsApi' do
    it 'should create an instance of SkillsApi' do
      expect(@api_instance).to be_instance_of(ESI::SkillsApi)
    end
  end

  # unit tests for get_characters_character_id_attributes
  # Get character attributes
  # Return attributes of a character
  # @param character_id The ID of the character
  # @param x_compatibility_date The compatibility date for the request.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :accept_language The language to use for the response.
  # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
  # @option opts [String] :x_tenant The tenant ID for the request.
  # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
  # @return [CharactersCharacterIdAttributesGet]
  describe 'get_characters_character_id_attributes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_characters_character_id_skillqueue
  # Get character&#39;s skill queue
  # List the configured skill queue for the given character.  Entries that have their finish time in the past are completed, but aren&#39;t updated in the \&quot;/skills\&quot; route yet. This will happen the next time the character logs in.
  # @param character_id The ID of the character
  # @param x_compatibility_date The compatibility date for the request.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :accept_language The language to use for the response.
  # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
  # @option opts [String] :x_tenant The tenant ID for the request.
  # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
  # @return [Array<CharactersSkillqueueSkill>]
  describe 'get_characters_character_id_skillqueue test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_characters_character_id_skills
  # Get character skills
  # List all trained skills for the given character.  Skills returned by this route can be out-of-date if the character hasn&#39;t logged in since one or more skills completed training. Use the /skillqueue route to check for skills that completed training. Entries that are in the past need to be applied on top of this list to get an accurate view of the character&#39;s current skills.
  # @param character_id The ID of the character
  # @param x_compatibility_date The compatibility date for the request.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :accept_language The language to use for the response.
  # @option opts [String] :if_none_match The ETag of the previous request. A 304 will be returned if this matches the current ETag.
  # @option opts [String] :x_tenant The tenant ID for the request.
  # @option opts [String] :if_modified_since The date the resource was last modified. A 304 will be returned if the resource has not been modified since this date.
  # @return [CharactersSkills]
  describe 'get_characters_character_id_skills test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
