=begin
#EVE Stable Infrastructure (ESI) - tranquility

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2020-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ESI::CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ESI::CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails do
  #let(:instance) { ESI::CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails.new }

  describe 'test an instance of CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails' do
    it 'should create an instance of CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(ESI::CharactersCharacterIdPlanetsPlanetIdGetPinsInnerExtractorDetails)
    end
  end

  describe 'test attribute "cycle_time"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "head_radius"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "heads"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "product_type_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "qty_per_cycle"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
