=begin
#EVE Stable Infrastructure (ESI) - tranquility

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2020-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ESI::FwLeaderboardsGetVictoryPoints
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ESI::FwLeaderboardsGetVictoryPoints do
  #let(:instance) { ESI::FwLeaderboardsGetVictoryPoints.new }

  describe 'test an instance of FwLeaderboardsGetVictoryPoints' do
    it 'should create an instance of FwLeaderboardsGetVictoryPoints' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(ESI::FwLeaderboardsGetVictoryPoints)
    end
  end

  describe 'test attribute "active_total"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "last_week"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "yesterday"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
