=begin
#EVE Stable Infrastructure (ESI) - tranquility

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2020-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ESI::FwWarsGetInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ESI::FwWarsGetInner do
  #let(:instance) { ESI::FwWarsGetInner.new }

  describe 'test an instance of FwWarsGetInner' do
    it 'should create an instance of FwWarsGetInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(ESI::FwWarsGetInner)
    end
  end

  describe 'test attribute "against_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "faction_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
