=begin
#EVE Stable Infrastructure (ESI) - tranquility

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2020-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ESI::PostFleetsFleetIdMembersRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ESI::PostFleetsFleetIdMembersRequest do
  #let(:instance) { ESI::PostFleetsFleetIdMembersRequest.new }

  describe 'test an instance of PostFleetsFleetIdMembersRequest' do
    it 'should create an instance of PostFleetsFleetIdMembersRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(ESI::PostFleetsFleetIdMembersRequest)
    end
  end

  describe 'test attribute "character_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "role"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["fleet_commander", "wing_commander", "squad_commander", "squad_member"])
      # validator.allowable_values.each do |value|
      #   expect { instance.role = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "squad_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "wing_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
