=begin
#EVE Stable Infrastructure (ESI) - tranquility

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2020-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ESI::PostCharactersCharacterIdMailRequestRecipientsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ESI::PostCharactersCharacterIdMailRequestRecipientsInner do
  #let(:instance) { ESI::PostCharactersCharacterIdMailRequestRecipientsInner.new }

  describe 'test an instance of PostCharactersCharacterIdMailRequestRecipientsInner' do
    it 'should create an instance of PostCharactersCharacterIdMailRequestRecipientsInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(ESI::PostCharactersCharacterIdMailRequestRecipientsInner)
    end
  end

  describe 'test attribute "recipient_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "recipient_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["alliance", "character", "corporation", "mailing_list"])
      # validator.allowable_values.each do |value|
      #   expect { instance.recipient_type = value }.not_to raise_error
      # end
    end
  end

end
