=begin
#EVE Stable Infrastructure (ESI) - tranquility

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2020-01-01

Generated by: https://openapi-generator.tech
Generator version: 7.20.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ESI::UniversePlanetsPlanetIdGet
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ESI::UniversePlanetsPlanetIdGet do
  #let(:instance) { ESI::UniversePlanetsPlanetIdGet.new }

  describe 'test an instance of UniversePlanetsPlanetIdGet' do
    it 'should create an instance of UniversePlanetsPlanetIdGet' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(ESI::UniversePlanetsPlanetIdGet)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "planet_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "position"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "system_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "type_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
